# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

run:
  timeout: 5m
  skip-files:
    - "^zz_generated.*"
  build-tags:
    - "e2e"

linters:
  disable-all: true
  enable:
    - containedctx
    - contextcheck
    - depguard
    - errcheck
    - errchkjson
    - errname
    - gochecknoinits
    - gci
    - goconst
    - gocritic
    - godot
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: k8s.io/kubernetes
            desc: "Do not use k8s.io/kubernetes directly"
  errcheck:
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/mesosphere)
      - Prefix(github.com/mesosphere/dynamic-credential-provider)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofumpt:
    lang-version: "1.17"
    extra-rules: true
  lll:
    line-length: 120
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    max-open-files: 2048
    severity: error
    rules:
      - name: add-constant
        arguments:
          - maxLitCount: "3"
            allowStrs: '"","testdata"'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: argument-limit
        arguments: [4]
      - name: comment-spacings
        arguments:
          - nolint
      - name: cognitive-complexity
        disabled: true
      - name: function-length
        arguments: [30, 0]
      - name: max-public-structs
        arguments: [10]
      - name: file-header
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cyclomatic
        arguments: [10]
      - name: function-result-limit
        arguments: [4]
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel

issues:
  exclude-rules:
    # ignore errcheck for code under a /test folder
    - path: "test/*"
      linters:
        - errcheck
    # ignore errcheck for flags.Parse (it is expected that we flag.ExitOnError)
    # ignore response.WriteError as it always returns the err it was passed
    - source: "flags.Parse|response.WriteError"
      linters:
        - errcheck
