# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

project_name: dynamic-credential-provider

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^build:'

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/mesosphere/dynamic-credential-provider/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - id: dynamic-credential-provider
    dir: ./cmd/dynamic-credential-provider
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      pre:
        - cmd: make go-generate
          env:
            - GOOS={{ .Os }}
            - GOARCH={{ .Arch }}
  - id: static-credential-provider
    dir: ./cmd/static-credential-provider
    binary: static-credential-provider
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      pre:
        - cmd: make go-generate
          env:
            - GOOS={{ .Os }}
            - GOARCH={{ .Arch }}
upx:
  - enabled: "{{ .IsSnapshot }}"
    goos:
      - linux
    compress: "9"
    lzma: true
    ids:
      - dynamic-credential-provider
      - static-credential-provider
archives:
  - name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
    builds:
      - dynamic-credential-provider
    rlcp: true
  - name_template: 'static-credential-provider_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
    id: static-credential-provider
    builds:
      - static-credential-provider
    rlcp: true
dockers:
  - image_templates:
      # Specify the image tag including `-amd64` suffix if the build is not a snapshot build or is not being built on
      # arm64 machine. This allows for using the snapshot image build without the archtecture specific suffix
      # consistently on local machines, i.e. can always use `ghcr.io/mesosphere/dynamic-credential-provider:v<VERSION>` on the machine the snapshot
      # is built on.
      #
      # For a release build the `-amd64` suffix will always be included and the `docker_manifests` specification below
      # will create the final multiplatform manifest to be pushed to the registry.
      - 'ghcr.io/mesosphere/dynamic-credential-provider:v{{trimprefix .Version "v"}}{{ if or (not .IsSnapshot) (not (eq .Runtime.Goarch "amd64")) }}-amd64{{ end }}'
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - credential-providers
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=dynamic-credential-provider"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=GO_VERSION={{.Env.GO_VERSION}}"
      - "--build-arg=CLOUD_PROVIDER_GCP_VERSION={{.Env.CLOUD_PROVIDER_GCP_VERSION}}"
  - image_templates:
      # Specify the image tag including `-amd64v8` suffix if the build is not a snapshot build or is not being built on
      # arm64 machine. This allows for using the snapshot image build without the archtecture specific suffix
      # consistently on local machines, i.e. can always use `ghcr.io/mesosphere/dynamic-credential-provider:v<VERSION>` on the machine the snapshot
      # is built on.
      #
      # For a release build the `-amd64v8` suffix will always be included and the `docker_manifests` specification below
      # will create the final multiplatform manifest to be pushed to the registry.
    - 'ghcr.io/mesosphere/dynamic-credential-provider:v{{trimprefix .Version "v"}}{{ if or (not .IsSnapshot) (not (eq .Runtime.Goarch "arm64")) }}-arm64v8{{ end }}'
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - credential-providers
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=dynamic-credential-provider"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=GO_VERSION={{.Env.GO_VERSION}}"
      - "--build-arg=CLOUD_PROVIDER_GCP_VERSION={{.Env.CLOUD_PROVIDER_GCP_VERSION}}"
docker_manifests:
  - name_template: ghcr.io/mesosphere/dynamic-credential-provider:v{{trimprefix .Version "v"}}
    image_templates:
    - ghcr.io/mesosphere/dynamic-credential-provider:v{{trimprefix .Version "v"}}-amd64
    - ghcr.io/mesosphere/dynamic-credential-provider:v{{trimprefix .Version "v"}}-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incminor .Tag }}-dev"
