# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Run unit tests
        run: make test

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json

  e2e-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check e2e tests exist
        id: check_e2e_files
        uses: andstor/file-existence-action@v2
        with:
          files: "test/e2e/**/*.go"

      - name: Install asdf
        if: steps.check_e2e_files.outputs.files_exists == 'true'
        uses: asdf-vm/actions/setup@v1

      - name: Run e2e tests
        if: steps.check_e2e_files.outputs.files_exists == 'true'
        run: make e2e-test

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
          reporter: github-pr-review
          go_version: ${{ fromJson(steps.versions.outputs.tools).golang }}
          golangci_lint_version: v${{ fromJson(steps.versions.outputs.tools).golangci-lint }}

  generated:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Check generated files
        run: make go-generate

      - name: Verify no changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files

      - name: Fail if files have changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1

  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ fromJson(steps.versions.outputs.tools).golang }}
          check-latest: false
          cache: true

      - uses: mfinelli/setup-shfmt@v2
        with:
          shfmt-version: ${{ fromJson(steps.versions.outputs.tools).shfmt }}

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install helm-docs
        run: make install-tool.helm-docs

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --show-diff-on-failure
        env:
          SKIP: no-commit-to-branch,golangci-lint,go-generate
