# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: conventional-release-labels
on:
  pull_request_target:
    types:
      - opened
      - edited

defaults:
  run:
    shell: bash

jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - uses: bcoe/conventional-release-labels@v1
