# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7
        id: release-please
        with:
          release-type: go
          package-name: dynamic-credential-provider
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup github authentication to ensure Github's rate limits are not hit.
      - if: ${{ steps.release-please.outputs.release_created }}
        name: Configure nix GitHub access-tokens
        run: |
          mkdir -p ~/.config/nix
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >>~/.config/nix/nix.conf

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.6.1

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Release
        run: devbox run -- make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ steps.release-please.outputs.tag_name }}
          chart_version: ${{ steps.release-please.outputs.tag_name }}
          target_dir: repo
