# Copyright 2022-2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v4.1
        id: release-please

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Release
        run: devbox run -- make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ steps.release-please.outputs.tag_name }}
          chart_version: ${{ steps.release-please.outputs.tag_name }}
          target_dir: repo
